---
- name: Install nginx everywhere
  hosts: servers
  gather_facts: yes
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

- name: Configure frontends
  hosts: "frontend:frontend_vrack"
  gather_facts: yes
  become: yes
  tasks:
    - name: Template nginx configuration file
      ansible.builtin.template:
        src: frontend.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: restart
  handlers:
    - name: restart
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Configure backends
  hosts: "backend:backend_vrack"
  gather_facts: no
  become: yes
  tasks:
    - name: Template index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    - name: Template nginx configuration file
      ansible.builtin.template:
        src: backend.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: restart
  handlers:
    - name: restart
      ansible.builtin.service:
        name: nginx
        state: restarted
