---
- name: check-port
  hosts: all
  gather_facts: no
  become: no
  vars_prompt:
    - name: ip
      prompt: ip
      private: no
    - name: checkport
      prompt: port
      private: no
  tasks:
    - name: wait_for | waiting for instance to listen on port {{ checkport }}
      wait_for:
        host: "{{ ip }}"
        port: "{{ checkport }}"
        connect_timeout: 10
        delay: 10
        state: started
        sleep: 5
