---
- name: iptables
  hosts: "frontend:frontend_vrack"
  gather_facts: no
  become: yes
  tasks:
    - name: enable ipv4 ipforward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Add iptables postrouting
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        out_interface: ens3
        jump: MASQUERADE
